
import java.awt.Color;
import java.util.Timer;
import java.util.TimerTask;
import javax.swing.JOptionPane;

/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * NewJFrame.java
 *
 * Created on Oct 4, 2016, 12:41:11 PM
 */

/**
 *
 * @author flyers
 */
public class NewJFrame extends javax.swing.JFrame {
    int color=1;
    
    

    /** Creates new form NewJFrame */
    public NewJFrame() {
        initComponents();
        jLabel1.setText("10000");
        jLabel2.setText("10000");
        jLabel3.setText("10000");
        jLabel4.setText("10000");
        jLabel5.setText("10000");
        jLabel6.setText("10000");
        jLabel7.setText("0");
        jLabel8.setText("0");
        jLabel9.setText("0");
        jLabel10.setText("0");
        jLabel11.setText("0");
        jLabel12.setText("0");
        jTextField13.setVisible(false);
        jTextField14.setVisible(false);
        jTextField15.setVisible(false);
        jTextField16.setVisible(false);
        jTextField17.setVisible(false);
        jTextField18.setVisible(false);
        jTextField13.setText(jLabel1.getText());
        jTextField14.setText(jLabel2.getText());
        jTextField15.setText(jLabel3.getText());
        jTextField16.setText(jLabel4.getText());
        jTextField17.setText(jLabel5.getText());
        jTextField18.setText(jLabel6.getText());
        
        {
        final Timer timer=new Timer();
        TimerTask task=new TimerTask()
        {
          public void run()
          {
            
            if(color%2==1)
                {
                 jLabel15.setForeground(Color.WHITE);
                }
              
                if(color%2==0)
                {
                 jLabel15.setForeground(Color.YELLOW);
                 
                }
                
                if(color==100)
                {
                 color=0;
                 
                }
                color++;
     
            
          }
          
        };
        timer.scheduleAtFixedRate(task, 250, 250);
    }
        
       
        
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton6 = new javax.swing.JButton();
        jLabel17 = new javax.swing.JLabel();
        jButton17 = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jTextField2 = new javax.swing.JTextField();
        jTextField3 = new javax.swing.JTextField();
        jTextField4 = new javax.swing.JTextField();
        jTextField5 = new javax.swing.JTextField();
        jTextField6 = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jTextField7 = new javax.swing.JTextField();
        jTextField8 = new javax.swing.JTextField();
        jTextField9 = new javax.swing.JTextField();
        jTextField10 = new javax.swing.JTextField();
        jTextField11 = new javax.swing.JTextField();
        jTextField12 = new javax.swing.JTextField();
        jButton7 = new javax.swing.JButton();
        jButton8 = new javax.swing.JButton();
        jRadioButton1 = new javax.swing.JRadioButton();
        jRadioButton2 = new javax.swing.JRadioButton();
        jRadioButton3 = new javax.swing.JRadioButton();
        jRadioButton4 = new javax.swing.JRadioButton();
        jRadioButton5 = new javax.swing.JRadioButton();
        jRadioButton6 = new javax.swing.JRadioButton();
        jLabel13 = new javax.swing.JLabel();
        jButton9 = new javax.swing.JButton();
        jButton10 = new javax.swing.JButton();
        jButton11 = new javax.swing.JButton();
        jButton12 = new javax.swing.JButton();
        jButton13 = new javax.swing.JButton();
        jButton14 = new javax.swing.JButton();
        jButton15 = new javax.swing.JButton();
        jButton16 = new javax.swing.JButton();
        jTextField13 = new javax.swing.JTextField();
        jTextField14 = new javax.swing.JTextField();
        jTextField15 = new javax.swing.JTextField();
        jTextField16 = new javax.swing.JTextField();
        jTextField17 = new javax.swing.JTextField();
        jTextField18 = new javax.swing.JTextField();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();

        jButton6.setText("jButton6");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel17.setForeground(new java.awt.Color(255, 255, 255));
        jLabel17.setText("Credits:- Priyanshu Gupta      Vaibhav Sanghai      Deepankar Saini     Aaryaman Bhardawaj");
        getContentPane().add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 550, -1, -1));

        jButton17.setText("Reset All");
        jButton17.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton17ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton17, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 490, -1, 30));

        jButton1.setText("Add");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 330, -1, -1));

        jButton2.setText("Add");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 330, -1, -1));

        jButton3.setText("Add");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 330, -1, -1));

        jButton4.setText("Add");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton4, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 330, -1, -1));

        jButton5.setText("Add");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton5, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 330, -1, -1));

        jLabel1.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Score");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 230, 47, -1));

        jLabel2.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Score");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 230, 50, -1));

        jLabel3.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Score");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 230, 47, -1));

        jLabel4.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Score");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 230, 47, -1));

        jLabel5.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Score");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 230, 47, -1));

        jLabel6.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Score");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 230, 40, -1));

        jTextField1.setText("Player1");
        jTextField1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jTextField1KeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTextField1KeyTyped(evt);
            }
        });
        getContentPane().add(jTextField1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 200, 99, -1));

        jTextField2.setText("Player2");
        jTextField2.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jTextField2KeyReleased(evt);
            }
        });
        getContentPane().add(jTextField2, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 200, 99, -1));

        jTextField3.setText("Player3");
        jTextField3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField3ActionPerformed(evt);
            }
        });
        jTextField3.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jTextField3KeyReleased(evt);
            }
        });
        getContentPane().add(jTextField3, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 200, 99, -1));

        jTextField4.setText("Player4");
        jTextField4.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jTextField4KeyReleased(evt);
            }
        });
        getContentPane().add(jTextField4, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 200, 99, -1));

        jTextField5.setText("Player5");
        jTextField5.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jTextField5KeyReleased(evt);
            }
        });
        getContentPane().add(jTextField5, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 200, 99, -1));

        jTextField6.setText("Player6");
        jTextField6.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jTextField6KeyReleased(evt);
            }
        });
        getContentPane().add(jTextField6, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 200, 99, -1));

        jLabel7.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("Money");
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 250, -1, -1));

        jLabel8.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("Money");
        getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 250, -1, -1));

        jLabel9.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setText("Money");
        getContentPane().add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 250, -1, -1));

        jLabel10.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(255, 255, 255));
        jLabel10.setText("Money");
        getContentPane().add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 250, -1, -1));

        jLabel11.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(255, 255, 255));
        jLabel11.setText("Money");
        getContentPane().add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 250, -1, -1));

        jLabel12.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(255, 255, 255));
        jLabel12.setText("Money");
        getContentPane().add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 250, -1, -1));
        getContentPane().add(jTextField7, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 280, 57, -1));
        getContentPane().add(jTextField8, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 280, 57, -1));
        getContentPane().add(jTextField9, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 280, 57, -1));
        getContentPane().add(jTextField10, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 280, 57, -1));
        getContentPane().add(jTextField11, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 280, 57, -1));
        getContentPane().add(jTextField12, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 280, 57, -1));

        jButton7.setText("Add");
        jButton7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton7ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton7, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 330, -1, -1));

        jButton8.setText("Calculate");
        jButton8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton8ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton8, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 490, 106, 30));

        jRadioButton1.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jRadioButton1.setForeground(new java.awt.Color(255, 255, 255));
        jRadioButton1.setText("Player 1");
        jRadioButton1.setContentAreaFilled(false);
        getContentPane().add(jRadioButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 440, -1, -1));

        jRadioButton2.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jRadioButton2.setForeground(new java.awt.Color(255, 255, 255));
        jRadioButton2.setText("Player 2");
        jRadioButton2.setContentAreaFilled(false);
        jRadioButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jRadioButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 440, -1, -1));

        jRadioButton3.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jRadioButton3.setForeground(new java.awt.Color(255, 255, 255));
        jRadioButton3.setText("Player 3");
        jRadioButton3.setContentAreaFilled(false);
        jRadioButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton3ActionPerformed(evt);
            }
        });
        getContentPane().add(jRadioButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 440, -1, -1));

        jRadioButton4.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jRadioButton4.setForeground(new java.awt.Color(255, 255, 255));
        jRadioButton4.setText("Player 4");
        jRadioButton4.setContentAreaFilled(false);
        getContentPane().add(jRadioButton4, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 440, -1, -1));

        jRadioButton5.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jRadioButton5.setForeground(new java.awt.Color(255, 255, 255));
        jRadioButton5.setText("Player 5");
        jRadioButton5.setContentAreaFilled(false);
        getContentPane().add(jRadioButton5, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 440, -1, -1));

        jRadioButton6.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jRadioButton6.setForeground(new java.awt.Color(255, 255, 255));
        jRadioButton6.setText("Player 6");
        jRadioButton6.setContentAreaFilled(false);
        getContentPane().add(jRadioButton6, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 440, -1, -1));

        jLabel13.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(255, 255, 255));
        jLabel13.setLabelFor(jButton9);
        jLabel13.setText("Random Number ");
        getContentPane().add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 170, -1, -1));

        jButton9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/unnamed.png"))); // NOI18N
        jButton9.setToolTipText("Goes to Random Number Generator");
        jButton9.setActionCommand("<html>\nRandom\n<br>\n Number\n Generator\n</html>");
        jButton9.setBorderPainted(false);
        jButton9.setContentAreaFilled(false);
        jButton9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton9ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton9, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 0, 170, 170));

        jButton10.setText("Pack");
        jButton10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton10ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton10, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 390, -1, -1));

        jButton11.setText("Pack");
        jButton11.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton11ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton11, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 390, -1, -1));

        jButton12.setText("Pack");
        jButton12.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton12ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton12, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 390, -1, -1));

        jButton13.setText("Pack");
        jButton13.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton13ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton13, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 390, -1, -1));

        jButton14.setText("Pack");
        jButton14.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton14ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton14, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 390, -1, -1));

        jButton15.setText("Pack");
        jButton15.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton15ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton15, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 390, -1, -1));

        jButton16.setText("Undo (reset to last calculate)");
        jButton16.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton16ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton16, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 490, 219, 30));

        jTextField13.setText("jTextField13");
        getContentPane().add(jTextField13, new org.netbeans.lib.awtextra.AbsoluteConstraints(59, 100, 10, -1));

        jTextField14.setText("jTextField13");
        getContentPane().add(jTextField14, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 110, 9, -1));

        jTextField15.setText("jTextField13");
        getContentPane().add(jTextField15, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 120, 9, -1));

        jTextField16.setText("jTextField13");
        getContentPane().add(jTextField16, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 110, 9, -1));

        jTextField17.setText("jTextField13");
        getContentPane().add(jTextField17, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 100, 9, -1));

        jTextField18.setText("jTextField13");
        getContentPane().add(jTextField18, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 540, 9, -1));

        jLabel14.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(255, 255, 255));
        jLabel14.setText("Version 3.5");
        getContentPane().add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 20, -1, -1));

        jLabel15.setFont(new java.awt.Font("Times New Roman", 1, 48)); // NOI18N
        jLabel15.setForeground(new java.awt.Color(255, 255, 255));
        jLabel15.setText("<html> <u>Teen Patti</u></html>");
        jLabel15.setToolTipText("Game created by Priyanshu Gupta");
        jLabel15.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel15MouseClicked(evt);
            }
        });
        getContentPane().add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 70, -1, -1));

        jLabel16.setBackground(java.awt.SystemColor.inactiveCaption);
        jLabel16.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel16.setIcon(new javax.swing.ImageIcon(getClass().getResource("/edited final.png"))); // NOI18N
        getContentPane().add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(-40, 0, 730, 570));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton9ActionPerformed
        randomnumbergenerator n=new randomnumbergenerator();
        n.setVisible(true);
        this.dispose();        // TODO add your handling code here:
}//GEN-LAST:event_jButton9ActionPerformed

    private void jRadioButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton3ActionPerformed
        // TODO add your handling code here:
}//GEN-LAST:event_jRadioButton3ActionPerformed

    private void jRadioButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton2ActionPerformed
        // TODO add your handling code here:
}//GEN-LAST:event_jRadioButton2ActionPerformed

    private void jButton8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton8ActionPerformed
        double x=0;

        if (jRadioButton1.isSelected()) {
            x=x+1;
        }
        if (jRadioButton2.isSelected()) {
            x=x+1;
        }
        if (jRadioButton3.isSelected()) {
            x=x+1;
        }
        if (jRadioButton4.isSelected()) {
            x=x+1;
        }
        if (jRadioButton5.isSelected()) {
            x=x+1;
        }
        if (jRadioButton6.isSelected()) {
            x=x+1;
        }

        if(jRadioButton1.isSelected()) {
            double p=Double.parseDouble(jLabel7.getText());
            double q=Double.parseDouble(jLabel8.getText());
            double r=Double.parseDouble(jLabel9.getText());
            double s=Double.parseDouble(jLabel10.getText());
            double t=Double.parseDouble(jLabel11.getText());
            double u=Double.parseDouble(jLabel12.getText());
            double v=Double.parseDouble(jLabel1.getText());


            jLabel1.setText(((p+q+r+s+t+u)/x)+v+"");

        }
        if(jRadioButton2.isSelected()) {
            double p=Double.parseDouble(jLabel7.getText());
            double q=Double.parseDouble(jLabel8.getText());
            double r=Double.parseDouble(jLabel9.getText());
            double s=Double.parseDouble(jLabel10.getText());
            double t=Double.parseDouble(jLabel11.getText());
            double u=Double.parseDouble(jLabel12.getText());
            double v=Double.parseDouble(jLabel2.getText());

            jLabel2.setText(((p+q+r+s+t+u)/x)+v+"");
        }
        if(jRadioButton3.isSelected()) {
            double p=Double.parseDouble(jLabel7.getText());
            double q=Double.parseDouble(jLabel8.getText());
            double r=Double.parseDouble(jLabel9.getText());
            double s=Double.parseDouble(jLabel10.getText());
            double t=Double.parseDouble(jLabel11.getText());
            double u=Double.parseDouble(jLabel12.getText());
            double v=Double.parseDouble(jLabel3.getText());

            jLabel3.setText(((p+q+r+s+t+u)/x)+v+"");
        }
        if(jRadioButton4.isSelected()) {
            double p=Double.parseDouble(jLabel7.getText());
            double q=Double.parseDouble(jLabel8.getText());
            double r=Double.parseDouble(jLabel9.getText());
            double s=Double.parseDouble(jLabel10.getText());
            double t=Double.parseDouble(jLabel11.getText());
            double u=Double.parseDouble(jLabel12.getText());
            double v=Double.parseDouble(jLabel4.getText());

            jLabel4.setText(((p+q+r+s+t+u)/x)+v+"");
        }
        if(jRadioButton5.isSelected()) {
            double p=Double.parseDouble(jLabel7.getText());
            double q=Double.parseDouble(jLabel8.getText());
            double r=Double.parseDouble(jLabel9.getText());
            double s=Double.parseDouble(jLabel10.getText());
            double t=Double.parseDouble(jLabel11.getText());
            double u=Double.parseDouble(jLabel12.getText());
            double v=Double.parseDouble(jLabel5.getText());

            jLabel5.setText(((p+q+r+s+t+u)/x)+v+"");
        }
        if(jRadioButton6.isSelected()) {
            double p=Double.parseDouble(jLabel7.getText());
            double q=Double.parseDouble(jLabel8.getText());
            double r=Double.parseDouble(jLabel9.getText());
            double s=Double.parseDouble(jLabel10.getText());
            double t=Double.parseDouble(jLabel11.getText());
            double u=Double.parseDouble(jLabel12.getText());
            double v=Double.parseDouble(jLabel6.getText());

            jLabel6.setText(((p+q+r+s+t+u)/x)+v+"");
        }
        if (jRadioButton1.isSelected() || jRadioButton2.isSelected() || jRadioButton3.isSelected() || jRadioButton4.isSelected() || jRadioButton5.isSelected() || jRadioButton6.isSelected()) {
            jLabel7.setText("0");
            jLabel8.setText("0");
            jLabel9.setText("0");
            jLabel10.setText("0");
            jLabel11.setText("0");
            jLabel12.setText("0");
            jRadioButton1.setSelected(false);
            jRadioButton2.setSelected(false);
            jRadioButton3.setSelected(false);
            jRadioButton4.setSelected(false);
            jRadioButton5.setSelected(false);
            jRadioButton6.setSelected(false);
            jButton1.setEnabled(true);
            jButton2.setEnabled(true);
            jButton3.setEnabled(true);
            jButton4.setEnabled(true);
            jButton5.setEnabled(true);
            jButton7.setEnabled(true);
            jButton10.setEnabled(true);
            jButton11.setEnabled(true);
            jButton12.setEnabled(true);
            jButton13.setEnabled(true);
            jButton14.setEnabled(true);
            jButton15.setEnabled(true);
            jTextField13.setText(jLabel1.getText());
            jTextField14.setText(jLabel2.getText());
            jTextField15.setText(jLabel3.getText());
            jTextField16.setText(jLabel4.getText());
            jTextField17.setText(jLabel5.getText());
            jTextField18.setText(jLabel6.getText());
            
        } else {
            JOptionPane.showMessageDialog(this,"Select Winner");
        }


    }//GEN-LAST:event_jButton8ActionPerformed

    private void jButton7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton7ActionPerformed
if((Double.parseDouble(jTextField12.getText()))>0 && (Double.parseDouble(jTextField12.getText()))<=(Double.parseDouble(jLabel6.getText())))
       {
        double n=Double.parseDouble(jLabel12.getText());
        double m=Double.parseDouble(jTextField12.getText());
        jLabel12.setText(m+n+"");
        jLabel6.setText(((Double.parseDouble(jLabel6.getText()))-m)+"");
        jTextField12.setText("");
       }
       else
       {
           JOptionPane.showMessageDialog(this,"You Cannot enter this number");
       }// TODO add your handling code here:
}//GEN-LAST:event_jButton7ActionPerformed

    private void jTextField6KeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextField6KeyReleased
        jRadioButton6.setText(jTextField6.getText());          // TODO add your handling code here:
}//GEN-LAST:event_jTextField6KeyReleased

    private void jTextField5KeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextField5KeyReleased
        jRadioButton5.setText(jTextField5.getText());          // TODO add your handling code here:
}//GEN-LAST:event_jTextField5KeyReleased

    private void jTextField4KeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextField4KeyReleased
        jRadioButton4.setText(jTextField4.getText());          // TODO add your handling code here:
}//GEN-LAST:event_jTextField4KeyReleased

    private void jTextField3KeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextField3KeyReleased
        jRadioButton3.setText(jTextField3.getText());          // TODO add your handling code here:
}//GEN-LAST:event_jTextField3KeyReleased

    private void jTextField3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField3ActionPerformed
        // TODO add your handling code here:
}//GEN-LAST:event_jTextField3ActionPerformed

    private void jTextField2KeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextField2KeyReleased
        jRadioButton2.setText(jTextField2.getText());          // TODO add your handling code here:
}//GEN-LAST:event_jTextField2KeyReleased

    private void jTextField1KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextField1KeyTyped
        // TODO add your handling code here:
}//GEN-LAST:event_jTextField1KeyTyped

    private void jTextField1KeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextField1KeyReleased
        jRadioButton1.setText(jTextField1.getText());          // TODO add your handling code here:
}//GEN-LAST:event_jTextField1KeyReleased

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
if((Double.parseDouble(jTextField11.getText()))>0 && (Double.parseDouble(jTextField11.getText()))<=(Double.parseDouble(jLabel5.getText())))
       {
        double n=Double.parseDouble(jLabel11.getText());
        double m=Double.parseDouble(jTextField11.getText());
        jLabel11.setText(m+n+"");
        jLabel5.setText(((Double.parseDouble(jLabel5.getText()))-m)+"");
        jTextField11.setText("");
       }
       else
       {
           JOptionPane.showMessageDialog(this,"You Cannot enter this number");
       }// TODO add your handling code here:
}//GEN-LAST:event_jButton5ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
if((Double.parseDouble(jTextField10.getText()))>0 && (Double.parseDouble(jTextField10.getText()))<=(Double.parseDouble(jLabel4.getText())))
       {
        double n=Double.parseDouble(jLabel10.getText());
        double m=Double.parseDouble(jTextField10.getText());
        jLabel10.setText(m+n+"");
        jLabel4.setText(((Double.parseDouble(jLabel4.getText()))-m)+"");
        jTextField10.setText("");
       }
       else
       {
           JOptionPane.showMessageDialog(this,"You Cannot enter this number");
       } // TODO add your handling code here:
}//GEN-LAST:event_jButton4ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
if((Double.parseDouble(jTextField9.getText()))>0 && (Double.parseDouble(jTextField9.getText()))<=(Double.parseDouble(jLabel3.getText())))
       {
          double n=Double.parseDouble(jLabel9.getText());
        double m=Double.parseDouble(jTextField9.getText());
        jLabel9.setText(m+n+"");
        jLabel3.setText(((Double.parseDouble(jLabel3.getText()))-m)+"");
        jTextField9.setText("");
       }
       else
       {
           JOptionPane.showMessageDialog(this,"You Cannot enter this number");
       }      // TODO add your handling code here:
}//GEN-LAST:event_jButton3ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
 if((Double.parseDouble(jTextField8.getText()))>0 && (Double.parseDouble(jTextField8.getText()))<=(Double.parseDouble(jLabel2.getText())))
       {
         double n=Double.parseDouble(jLabel8.getText());
        double m=Double.parseDouble(jTextField8.getText());
        jLabel8.setText(m+n+"");
        jLabel2.setText(((Double.parseDouble(jLabel2.getText()))-m)+"");
        jTextField8.setText("");
       }
       else
       {
           JOptionPane.showMessageDialog(this,"You Cannot enter this number");
       }       
}//GEN-LAST:event_jButton2ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
       if((Double.parseDouble(jTextField7.getText()))>0 && (Double.parseDouble(jTextField7.getText()))<=(Double.parseDouble(jLabel1.getText())))
       {
        double n=Double.parseDouble(jLabel7.getText());
        double m=Double.parseDouble(jTextField7.getText());
        jLabel7.setText(m+n+"");
        jLabel1.setText(((Double.parseDouble(jLabel1.getText()))-m)+"");
        jTextField7.setText("");
       }
       else
       {
           JOptionPane.showMessageDialog(this,"You Cannot enter this number");
       }
}//GEN-LAST:event_jButton1ActionPerformed

    private void jButton10ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton10ActionPerformed
jButton1.setEnabled(false);
jButton10.setEnabled(false);

// TODO add your handling code here:
    }//GEN-LAST:event_jButton10ActionPerformed

    private void jButton11ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton11ActionPerformed
jButton2.setEnabled(false);
jButton11.setEnabled(false);// TODO add your handling code here:
    }//GEN-LAST:event_jButton11ActionPerformed

    private void jButton12ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton12ActionPerformed
jButton3.setEnabled(false);
jButton12.setEnabled(false);// TODO add your handling code here:
    }//GEN-LAST:event_jButton12ActionPerformed

    private void jButton13ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton13ActionPerformed
jButton4.setEnabled(false);
jButton13.setEnabled(false);// TODO add your handling code here:
    }//GEN-LAST:event_jButton13ActionPerformed

    private void jButton14ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton14ActionPerformed
jButton5.setEnabled(false);
jButton14.setEnabled(false);// TODO add your handling code here:
    }//GEN-LAST:event_jButton14ActionPerformed

    private void jButton15ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton15ActionPerformed
jButton7.setEnabled(false);
jButton15.setEnabled(false);// TODO add your handling code here:
    }//GEN-LAST:event_jButton15ActionPerformed

    private void jButton16ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton16ActionPerformed
jLabel1.setText(jTextField13.getText());
jLabel2.setText(jTextField14.getText());
jLabel3.setText(jTextField15.getText());
jLabel4.setText(jTextField16.getText());
jLabel5.setText(jTextField17.getText());
jLabel6.setText(jTextField18.getText());

jButton1.setEnabled(true);
            jButton2.setEnabled(true);
            jButton3.setEnabled(true);
            jButton4.setEnabled(true);
            jButton5.setEnabled(true);
            jButton7.setEnabled(true);
            jButton10.setEnabled(true);
            jButton11.setEnabled(true);
            jButton12.setEnabled(true);
            jButton13.setEnabled(true);
            jButton14.setEnabled(true);
            jButton15.setEnabled(true);
            jLabel7.setText("0");
            jLabel8.setText("0");
            jLabel9.setText("0");
            jLabel10.setText("0");
            jLabel11.setText("0");
            jLabel12.setText("0");
            jRadioButton1.setSelected(false);
            jRadioButton2.setSelected(false);
            jRadioButton3.setSelected(false);
            jRadioButton4.setSelected(false);
            jRadioButton5.setSelected(false);
            jRadioButton6.setSelected(false);

    }//GEN-LAST:event_jButton16ActionPerformed

    private void jLabel15MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel15MouseClicked
JOptionPane.showMessageDialog(this, "This game is created by Priyanshu Gupta");        // TODO add your handling code here:
    }//GEN-LAST:event_jLabel15MouseClicked

    private void jButton17ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton17ActionPerformed
int n=JOptionPane.showConfirmDialog(this, "Are you sure?\nThis will reset to its default State");
if (n==0)
{
   jLabel1.setText("10000");
        jLabel2.setText("10000");
        jLabel3.setText("10000");
        jLabel4.setText("10000");
        jLabel5.setText("10000");
        jLabel6.setText("10000");
        jLabel7.setText("0");
        jLabel8.setText("0");
        jLabel9.setText("0");
        jLabel10.setText("0");
        jLabel11.setText("0");
        jLabel12.setText("0");
        jTextField13.setVisible(false);
        jTextField14.setVisible(false);
        jTextField15.setVisible(false);
        jTextField16.setVisible(false);
        jTextField17.setVisible(false);
        jTextField18.setVisible(false);
        jTextField13.setText(jLabel1.getText());
        jTextField14.setText(jLabel2.getText());
        jTextField15.setText(jLabel3.getText());
        jTextField16.setText(jLabel4.getText());
        jTextField17.setText(jLabel5.getText());
        jTextField18.setText(jLabel6.getText()); 
        jTextField1.setText("Player 1");
        jTextField2.setText("Player 2");
        jTextField3.setText("Player 3");
        jTextField4.setText("Player 4");
        jTextField5.setText("Player 5");
        jTextField6.setText("Player 6");
        jRadioButton1.setText("Player 1");
        jRadioButton2.setText("Player 2");
        jRadioButton3.setText("Player 3");
        jRadioButton4.setText("Player 4");
        jRadioButton5.setText("Player 5");
        jRadioButton6.setText("Player 6");
}
    }//GEN-LAST:event_jButton17ActionPerformed

    /**
    * @param args the command line arguments
    */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new NewJFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton10;
    private javax.swing.JButton jButton11;
    private javax.swing.JButton jButton12;
    private javax.swing.JButton jButton13;
    private javax.swing.JButton jButton14;
    private javax.swing.JButton jButton15;
    private javax.swing.JButton jButton16;
    private javax.swing.JButton jButton17;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButton7;
    private javax.swing.JButton jButton8;
    private javax.swing.JButton jButton9;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JRadioButton jRadioButton1;
    private javax.swing.JRadioButton jRadioButton2;
    private javax.swing.JRadioButton jRadioButton3;
    private javax.swing.JRadioButton jRadioButton4;
    private javax.swing.JRadioButton jRadioButton5;
    private javax.swing.JRadioButton jRadioButton6;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField10;
    private javax.swing.JTextField jTextField11;
    private javax.swing.JTextField jTextField12;
    private javax.swing.JTextField jTextField13;
    private javax.swing.JTextField jTextField14;
    private javax.swing.JTextField jTextField15;
    private javax.swing.JTextField jTextField16;
    private javax.swing.JTextField jTextField17;
    private javax.swing.JTextField jTextField18;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField3;
    private javax.swing.JTextField jTextField4;
    private javax.swing.JTextField jTextField5;
    private javax.swing.JTextField jTextField6;
    private javax.swing.JTextField jTextField7;
    private javax.swing.JTextField jTextField8;
    private javax.swing.JTextField jTextField9;
    // End of variables declaration//GEN-END:variables

}
