
import java.awt.Color;
import java.util.Timer;
import java.util.TimerTask;
import javax.swing.JOptionPane;

/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * randomnumbergenerator.java
 *
 * Created on Oct 18, 2016, 8:34:37 AM
 */

/**
 *
 * @author flyers
 */
public class randomnumbergenerator extends javax.swing.JFrame {
int x=0;
int y=0;
int z=0;
int color1=0;
int color2=0;
int color3=0;
int total=0;


    int sec=7;
    int color=0;
         {
        final Timer timer1=new Timer();
        TimerTask task1=new TimerTask()
        {
          public void run()
          {
            
            if(color%2==1)
                {
                 jLabel2.setForeground(Color.WHITE);
                }
              
                if(color%2==0)
                {
                 jLabel2.setForeground(Color.YELLOW);
                 
                }
                
                if(color==100)
                {
                 color=0;
                 
                }
                color++;
     
          }
          
        };
        timer1.scheduleAtFixedRate(task1, 200, 200);
    }

    /** Creates new form randomnumbergenerator */
    public randomnumbergenerator() {
        initComponents();
        
        
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel8 = new javax.swing.JLabel();
        jButton6 = new javax.swing.JButton();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jToggleButton1 = new javax.swing.JToggleButton();
        jLabel7 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel8.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("Total");
        getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 100, -1, -1));

        jButton6.setText("Reset All");
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton6, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 240, 100, -1));

        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel9.setText("****");
        getContentPane().add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 90, 70, -1));

        jLabel10.setForeground(new java.awt.Color(255, 255, 255));
        jLabel10.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel10.setText("****");
        getContentPane().add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 90, 70, -1));

        jLabel11.setForeground(new java.awt.Color(255, 255, 255));
        jLabel11.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel11.setText("****");
        getContentPane().add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 90, 70, -1));

        jButton3.setBackground(new java.awt.Color(255, 255, 255));
        jButton3.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        jButton3.setForeground(new java.awt.Color(255, 255, 255));
        jButton3.setText("14");
        getContentPane().add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 110, 50, 60));

        jButton4.setBackground(new java.awt.Color(255, 255, 255));
        jButton4.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        jButton4.setForeground(new java.awt.Color(255, 255, 255));
        jButton4.setText("14");
        getContentPane().add(jButton4, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 110, 50, 60));

        jButton5.setBackground(new java.awt.Color(255, 255, 255));
        jButton5.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        jButton5.setForeground(new java.awt.Color(255, 255, 255));
        jButton5.setText("14");
        getContentPane().add(jButton5, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 110, 50, 60));

        jLabel6.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setLabelFor(jToggleButton1);
        jLabel6.setText("Calculator");
        jLabel6.setToolTipText("");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 200, -1, -1));

        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Execution number");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 40, -1, -1));

        jLabel2.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Random Cards Generator");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 10, -1, -1));

        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("0");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 40, 50, -1));

        jLabel4.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Your generated Cards are-");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 60, -1, -1));

        jLabel5.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("****");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 130, 40, -1));

        jButton1.setText("Generate");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 190, 109, -1));

        jButton2.setText("Show");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 190, 109, -1));

        jToggleButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/unnamed.png"))); // NOI18N
        jToggleButton1.setToolTipText("Goes to Calculator");
        jToggleButton1.setBorderPainted(false);
        jToggleButton1.setContentAreaFilled(false);
        jToggleButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jToggleButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jToggleButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 30, 170, 170));

        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Flames_black_red.jpg"))); // NOI18N
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(-410, -360, 950, 630));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed


if(total==0)
{
 JOptionPane.showMessageDialog(this,"Please first Generate a number");   
}
else
{
String sh=jButton2.getText();

if(sh.equals("Show"))
{
 jLabel5.setText(total+"");
 jButton2.setText("Hide");

 {if (color1==1)
 {
  jLabel9.setText("Diamonds");
  jButton3.setBackground(Color.red);
 }
 if (color1==2)
 {
  jLabel9.setText("Hearts");
  jButton3.setBackground(Color.red);
 }
 if (color1==3)
 {
  jLabel9.setText("Clubs");
  jButton3.setBackground(Color.BLACK);
 }
 if (color1==4)
 {
  jLabel9.setText("Spades");
  jButton3.setBackground(Color.BLACK);
 }}


 {if (color2==1)
 {
  jLabel10.setText("Diamonds");
  jButton4.setBackground(Color.red);
 }
 if (color2==2)
 {
  jLabel10.setText("Hearts");
  jButton4.setBackground(Color.red);
 }
 if (color2==3)
 {
  jLabel10.setText("Clubs");
  jButton4.setBackground(Color.BLACK);
 }
 if (color2==4)
 {
  jLabel10.setText("Spades");
  jButton4.setBackground(Color.BLACK);
 }}


 {if (color3==1)
 {
  jLabel11.setText("Diamonds");
  jButton5.setBackground(Color.red);
 }
 if (color3==2)
 {
  jLabel11.setText("Hearts");
  jButton5.setBackground(Color.red);
 }
 if (color3==3)
 {
  jLabel11.setText("Clubs");
  jButton5.setBackground(Color.BLACK);
 }
 if (color3==4)
 {
  jLabel11.setText("Spades");
  jButton5.setBackground(Color.BLACK);
 }}


 {if(x==14)
  {
   jButton3.setText("A");
  }
  if(x==13)
  {
   jButton3.setText("K");
  }
  if(x==12)
  {
  jButton3.setText("Q");
  }
  if(x==11)
  {
  jButton3.setText("J");
  }
  if((x==2)||(x==3)||(x==4)||(x==5)||(x==6)||(x==7)||(x==8)||(x==9)||(x==10)) 
  {
  jButton3.setText(x+"");    
  }}
  
  
  
  {if(y==14)
  {
   jButton4.setText("A");
  }
  if(y==13)
  {
   jButton4.setText("K");
  }
  if(y==12)
  {
   jButton4.setText("Q");
  }
  if(y==11)
  {
  jButton4.setText("J");
  }
  if((y==2)||(y==3)||(y==4)||(y==5)||(y==6)||(y==7)||(y==8)||(y==9)||(y==10)) 
  {
  jButton4.setText(y+"");    
  }}
    
  
    {if(z==14)
  {
  jButton5.setText("A");
  }
  if(z==13)
  {
  jButton5.setText("K");
  }
  if(z==12)
  {
  jButton5.setText("Q");
  }
  if(z==11)
  {
  jButton5.setText("J");
  }
  if((z==2)||(z==3)||(z==4)||(z==5)||(z==6)||(z==7)||(z==8)||(z==9)||(z==10))
  {
   jButton5.setText(z+"");      
  }}

}
else if(sh.equals("Hide"))
{
jLabel5.setText("****");
jButton2.setText("Show");
jButton3.setText("*");
jButton4.setText("*");
jButton5.setText("*");
jButton3.setBackground(Color.WHITE);
jButton4.setBackground(Color.WHITE);
jButton5.setBackground(Color.WHITE);
jLabel9.setText("****");
jLabel10.setText("****");
jLabel11.setText("****");
}
}
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
x=0;
y=0;
z=0;
color1=0;
color2=0;
color3=0;

while((x>14 || x<2) || (color1>4 || color1<1))
{
 x=((int)(Math.random()*100));
 color1=((int)(Math.random()*100));
}

while((y>14 || y<2) || (color2>4 || color2<1) || ((color2==color1) && (y==x)))
{
 y=((int)(Math.random()*100));
 color2=((int)(Math.random()*100));
}

while((z>14 || z<2) || (color3>4 || color3<1) ||( (color3==color2) && (z==y) ) || ( (color3==color1) && (z==x)))
{
 z=((int)(Math.random()*100));
 color3=((int)(Math.random()*100));
}
total=x+y+z;

jButton3.setText("#");
jButton4.setText("#");
jButton5.setText("#");
jButton3.setBackground(Color.WHITE);
jButton4.setBackground(Color.WHITE);
jButton5.setBackground(Color.WHITE);
jLabel5.setText("####");
jLabel9.setText("##");
jLabel10.setText("##");
jLabel11.setText("##");



jLabel3.setText(Integer.parseInt(jLabel3.getText())+1+"");
jButton2.setText("Show");
jButton1.setEnabled(false);

        final Timer timer=new Timer();
        TimerTask task=new TimerTask()
        {
          public void run()
          {
             jButton1.setText(sec+"");
             sec--;
             if(sec==0)
              {
               timer.cancel();
               jButton1.setEnabled(true);
               jButton1.setText("Generate");
               sec=7;
              }
          }
          
        };
        timer.scheduleAtFixedRate(task, 1000, 1000);

    }//GEN-LAST:event_jButton1ActionPerformed

    private void jToggleButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jToggleButton1ActionPerformed
NewJFrame n=new NewJFrame();
n.setVisible(true);
this.dispose();
    }//GEN-LAST:event_jToggleButton1ActionPerformed

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
int n=JOptionPane.showConfirmDialog(this, "Are you sure?\nThis will reset to its default State");
if (n==0)
{
  jLabel3.setText("0");
x=0;
y=0;
z=0;
color1=0;
color2=0;
color3=0;
total=0;

jLabel5.setText("****");
jButton2.setText("Show");
jButton3.setText("*");
jButton4.setText("*");
jButton5.setText("*");
jButton3.setBackground(Color.WHITE);
jButton4.setBackground(Color.WHITE);
jButton5.setBackground(Color.WHITE);
jLabel9.setText("****");
jLabel10.setText("****");
jLabel11.setText("****");



}
    }//GEN-LAST:event_jButton6ActionPerformed

    /**
    * @param args the command line arguments
    */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new randomnumbergenerator().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JToggleButton jToggleButton1;
    // End of variables declaration//GEN-END:variables

}
